openapi: "3.0.0"
info:
  title: Harvested API
  description: |-
    This API produces details of the harvested crops
  version: 0.0.1

paths:
  /harvested/crops/{season}:
    get:
      summary: List of all harvested crops
      operationId: getHarvestedCropsDetailsBySeason
      parameters:
        - name: season
          required: true
          description: Planting season
          in: path
          schema:
            type: string

      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/harvestedCropDetailsResponse'
components:
  schemas:
    harvestedCropDetailsResponse:
      type: object
      properties:
        farms:
          type: array
          items:
            $ref: '#/components/schemas/farm'


    farm:
      type: object
      properties:
        name:
          type: string
        season:
          type: string
        crops:
          type: array
          items:
            $ref: '#/components/schemas/crop'

    crop:
      type: object
      properties:
        name:
          type: string
        harvestedAmount:
          type: integer

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string